export interface Guest {
  id: string;
  name: string;
}

export interface Table {
  id: number;
  name: string;
  guests: Guest[];
  seats: number;
}

export type NewGuest = {
  name: string;
  table: number;
};

export type TableInfo = {
  number: number;
  name: string;
  guests: string[];
  x: string;
  y: string;
};

export const NewTables: TableInfo[] = [
  {
    number: 1,
    name: 'Andromeda',
    x: '78%',
    y: '24%',
    guests: [
      'Rosa',
      'Ângelo',
      'Anabela',
      'Pedro',
      'Ana Flor',
      'Feliciano',
      'Anđela',
      'Avó Emília',
      'Fátima',
    ],
  },
  {
    number: 2,
    name: 'Orion',
    x: '86%',
    y: '38%',
    guests: [
      'Palmira',
      'Aurélio',
      'Avô Chiquinho',
      'Avó Livinha',
      'Abílio',
      'Cristina',
      'Manuel',
      'Sandra',
      'Teresa',
      'José',
    ],
  },
  {
    number: 3,
    name: 'Hydra',
    x: '84%',
    y: '56%',
    guests: [
      'Emília',
      'Manuel',
      'Cristina',
      'Albano',
      'Célia',
      'Nelo',
      'Carmo',
      'Adriano',
      'Conceição',
      'Carlos',
      'Belém',
    ],
  },
  {
    number: 4,
    name: 'Cassiopeia',
    x: '72%',
    y: '72%',
    guests: [
      'José',
      'Beatriz',
      'Ana',
      'Catarina',
      'Beatriz L.',
      'Jorge',
      'Pedro',
      'João R.',
      'Daniela',
      'Leo',
    ],
  },
  {
    number: 5,
    name: 'Centaurus',
    x: '55%',
    y: '82%',
    guests: [
      'Tiago',
      'Sara',
      'Adriana',
      'João',
      'Leonor',
      'Beatriz S.',
      'Marcelo',
      'Beatriz C.',
      'Bruna',
      'Pedro',
    ],
  },
  {
    number: 6,
    name: 'Lyra',
    x: '38%',
    y: '82%',
    guests: [
      'Salete',
      'Rosa',
      'César',
      'Sérgio',
      'Lúcia',
      'Deolinda',
      'Domingos',
      'Avó Aurora',
    ],
  },
  {
    number: 7,
    name: 'Pegasus',
    x: '22%',
    y: '72%',
    guests: [
      'Sérgio',
      'Helena',
      'Luísa',
      'José',
      'Susana',
      'João',
      'Leonel',
      'Inês',
      'Alice',
    ],
  },
  {
    number: 8,
    name: 'Perseus',
    x: '12%',
    y: '56%',
    guests: [
      'Carina',
      'Tó',
      'Gonçalo',
      'Bruno',
      'Marlene',
      'Matilde',
      'Josefa',
      'Manuel',
    ],
  },
  {
    number: 9,
    name: 'Cepheus',
    x: '14%',
    y: '38%',
    guests: [
      'Sylviane',
      'Ricardo',
      'Matilde',
      'Clara',
      'Angelique',
      'Ricardo',
      'Afonso',
      'Luísa',
      'Priscila',
      'Laura',
    ],
  },
  {
    number: 10,
    name: 'Draco',
    x: '30%',
    y: '20%',
    guests: [
      'João Monteiro',
      'Liliana',
      'Daniel Costa',
      'Raquel Fernandes',
      'Henrique',
      'Raquel',
      'Diogo Costa',
      'Diogo Leite',
      'Eliana Magano',
      'Margarida',
      'Bruno',
      'Adriana',
      'Miguel Pinto',
      'Juliana',
      'Marco',
      'Sofia',
    ],
  },
  {
    number: 11,
    name: 'Aquila',
    x: '54%',
    y: '20%',
    guests: [
      'Margarida',
      'Paulinho',
      'Francisca',
      'João',
      'Estela',
      'Pedro',
      'Anabela',
      'Lucas Martins',
      'Mónica',
      'André',
      'Inês',
      'João',
      'Tiago',
      'Venus',
      'Francisca',
      'Gabriela',
      'José',
    ],
  },
];

export const TABLE_LAYOUT: Record<number, React.CSSProperties> = {
  // esquerda
  5: { left: '18%', top: '22%', width: '120px', height: '120px' },
  7: { left: '7%',  top: '44%', width: '70px',  height: '70px'  },
  3: { left: '20%', top: '59%', width: '130px', height: '130px' },
  9: { left: '9%',  top: '79%', width: '120px', height: '120px' },
  1: { left: '21%', top: '88%', width: '100px', height: '100px' },
  // direita
  8: { left: '93%', top: '25%', width: '70px',  height: '70px'  },
  6: { left: '83%', top: '37%', width: '90px',  height: '90px'  },
  4: { left: '89%', top: '61%', width: '140px', height: '140px' },
  2: { left: '83%', top: '86%', width: '130px', height: '130px' },
  // retangulares — left/right edges kept clear of PISTA (460–740px)
  11: { left: '34%', top: '50%', width: '80px', height: '490px' },
  10: { left: '66%', top: '47%', width: '80px', height: '380px' },
};

export const tables: Table[] = [
  {
    id: 1,
    name: 'Andromeda',
    guests: [
      { id: '1', name: 'Rosa' },
      { id: '2', name: 'Ângelo' },
      { id: '3', name: 'Anabela' },
      { id: '4', name: 'Pedro' },
      { id: '5', name: 'Ana Flor' },
      { id: '6', name: 'Feliciano' },
      { id: '7', name: 'Anđela' },
      { id: '8', name: 'Avó Emília' },
      { id: '9', name: 'Fátima' },
    ],
    seats: 10,
  },
  {
    id: 2,
    name: 'Orion',
    guests: [
      { id: '1', name: 'Aurélio' },
      { id: '2', name: 'Palmira' },
      { id: '3', name: 'Avô Chiquinho' },
      { id: '4', name: 'Avó Livinha' },
      { id: '5', name: 'Abílio' },
      { id: '6', name: 'Cristina' },
      { id: '7', name: 'Manuel' },
      { id: '8', name: 'Sandra' },
      { id: '9', name: 'Teresa' },
      { id: '10', name: 'José' },
    ],
    seats: 10,
  },
  {
    id: 3,
    name: 'Hydra',
    guests: [
      { id: '1', name: 'Emília' },
      { id: '2', name: 'Manuel' },
      { id: '3', name: 'Cristina' },
      { id: '4', name: 'Albano' },
      { id: '5', name: 'Célia' },
      { id: '6', name: 'Nelo' },
      { id: '7', name: 'Carmo' },
      { id: '8', name: 'Adriano' },
      { id: '9', name: 'Conceição' },
      { id: '10', name: 'Carlos' },
      { id: '11', name: 'Belém' },
    ],
    seats: 11,
  },
  {
    id: 4,
    name: 'Cassiopeia',
    guests: [
      { id: '1', name: 'Beatriz A.' },
      { id: '2', name: 'José' },
      { id: '3', name: 'Ana' },
      { id: '4', name: 'Catarina' },
      { id: '5', name: 'Beatriz L.' },
      { id: '6', name: 'Jorge' },
      { id: '7', name: 'Pedro' },
      { id: '8', name: 'João R.' },
      { id: '9', name: 'Daniela' },
      { id: '10', name: 'Leo' },
    ],
    seats: 10,
  },
  {
    id: 5,
    name: 'Centaurus',
    guests: [
      { id: '1', name: 'Tiago' },
      { id: '2', name: 'Sara' },
      { id: '3', name: 'Adriana' },
      { id: '4', name: 'João' },
      { id: '5', name: 'Leonor' },
      { id: '6', name: 'Beatriz S.' },
      { id: '7', name: 'Marcelo' },
      { id: '8', name: 'Beatriz C.' },
      { id: '9', name: 'Bruna' },
      { id: '10', name: 'Pedro' },
    ],
    seats: 10,
  },
  {
    id: 6,
    name: 'Lyra',
    guests: [
      { id: '1', name: 'Salete' },
      { id: '2', name: 'Rosa' },
      { id: '3', name: 'César' },
      { id: '4', name: 'Lúcia' },
      { id: '5', name: 'Sérgio' },
      { id: '6', name: 'Deolinda' },
      { id: '7', name: 'Domingos' },
      { id: '8', name: 'Avó Aurora' },
    ],
    seats: 7,
  },
  {
    id: 7,
    name: 'Pegasus',
    guests: [
      { id: '1', name: 'Sérgio' },
      { id: '2', name: 'Helena' },
      { id: '3', name: 'Luísa' },
      { id: '4', name: 'José' },
      { id: '5', name: 'Susana' },
      { id: '6', name: 'João' },
      { id: '7', name: 'Leonel' },
      { id: '8', name: 'Inês' },
      { id: '9', name: 'Alice' },
    ],
    seats: 9,
  },
  {
    id: 8,
    name: 'Perseus',
    guests: [
      { id: '1', name: 'Carina' },
      { id: '2', name: 'António' },
      { id: '3', name: 'Gonçalo' },
      { id: '4', name: 'Bruno' },
      { id: '5', name: 'Marlene' },
      { id: '6', name: 'Matilde' },
      { id: '7', name: 'Josefa' },
      { id: '8', name: 'Manuel' },
    ],
    seats: 8,
  },
  {
    id: 9,
    name: 'Cepheus',
    guests: [
      { id: '1', name: 'Sylviane' },
      { id: '2', name: 'Ricardo' },
      { id: '3', name: 'Matilde' },
      { id: '4', name: 'Clara' },
      { id: '5', name: 'Angelique' },
      { id: '6', name: 'Ricardo' },
      { id: '7', name: 'Afonso' },
      { id: '8', name: 'Luísa' },
      { id: '9', name: 'Priscila' },
      { id: '10', name: 'Laura' },
    ],
    seats: 10,
  },
  {
    id: 10,
    name: 'Draco',
    guests: [
      { id: '1', name: 'João' },
      { id: '2', name: 'Liliana' },
      { id: '3', name: 'Daniel' },
      { id: '4', name: 'Raquel' },
      { id: '5', name: 'Diogo' },
      { id: '6', name: 'Eliana' },
      { id: '7', name: 'Margarida' },
      { id: '8', name: 'Henrique' },
      { id: '9', name: 'Raquel' },
      { id: '10', name: 'Diogo C.' },
      { id: '11', name: 'Bruno' },
      { id: '12', name: 'Adriana' },
      { id: '13', name: 'Miguel' },
      { id: '14', name: 'Juliana' },
      { id: '15', name: 'Marco' },
      { id: '16', name: 'Sofia' },
    ],
    seats: 16,
  },
  {
    id: 11,
    name: 'Aquila',
    guests: [
      { id: '1', name: 'Margarida' },
      { id: '2', name: 'Paulo' },
      { id: '3', name: 'Francisca' },
      { id: '4', name: 'João' },
      { id: '5', name: 'Estela' },
      { id: '6', name: 'Pedro' },
      { id: '7', name: 'Anabela' },
      { id: '8', name: 'Lucas' },
      { id: '9', name: 'Mónica' },
      { id: '10', name: 'André' },
      { id: '11', name: 'Inês' },
      { id: '12', name: 'João C.' },
      { id: '13', name: 'Tiago' },
      { id: '14', name: 'Venus' },
      { id: '15', name: 'Francisca' },
      { id: '16', name: 'Gabriela' },
      { id: '17', name: 'José' },
    ],
    seats: 17,
  },
];
