export interface Guest {
  id: string;
  name: string;
}

export interface Table {
  id: number;
  name: string;
  guests: Guest[];
}

export const tables: Table[] = [
  {
    id: 1,
    name: 'Time',
    guests: [
      { id: '1', name: 'Pai' },
      { id: '2', name: 'Mãe' },
      { id: '3', name: 'Avô Chiquinho' },
      { id: '4', name: 'Avó Livinha' },
      { id: '5', name: 'Tio ABílio' },
      { id: '6', name: 'Tia Cristina' },
      { id: '7', name: 'Padrinho' },
      { id: '8', name: 'Madrinha' },
      { id: '9', name: 'Teresa' },
      { id: '10', name: 'José' },
    ],
  },
  {
    id: 2,
    name: 'Love',
    guests: [
      { id: '1', name: 'Mãe' },
      { id: '2', name: 'Ângelo' },
      { id: '3', name: 'Bela' },
      { id: '4', name: 'Pedro' },
      { id: '5', name: 'Flor' },
      { id: '6', name: 'Lua' },
      { id: '7', name: 'Fell' },
      { id: '8', name: 'Andela' },
      { id: '9', name: 'Avó' },
    ],
  },
  {
    id: 3,
    name: 'Millers Planet',
    guests: [
      { id: '1', name: 'João' },
      { id: '2', name: 'Liliana' },
      { id: '3', name: 'Diogo Leite' },
      { id: '4', name: 'Eliana' },
      { id: '5', name: 'Daniel' },
      { id: '6', name: 'Raquel Fernandes' },
      { id: '7', name: 'Henrique' },
      { id: '8', name: 'Raquel Carvalho' },
      { id: '9', name: 'Diogo Costa' },
    ],
  },
  {
    id: 4,
    name: 'Manns Planet',
    guests: [
      { id: '1', name: 'Magui' },
      { id: '2', name: 'Paulinho' },
      { id: '3', name: 'Estela' },
      { id: '4', name: 'Pedro' },
      { id: '5', name: 'Chiquinha' },
      { id: '6', name: 'João' },
      { id: '7', name: 'Bea' },
      { id: '8', name: 'Célio' },
      { id: '9', name: 'Bárbara' },
      { id: '10', name: 'André' },
    ],
  },
  {
    id: 5,
    name: 'Edmunds Planet',
    guests: [
      { id: '1', name: 'Mónica' },
      { id: '2', name: 'Tito' },
      { id: '3', name: 'Vaughn' },
      { id: '4', name: 'Gabriela' },
      { id: '5', name: 'José' },
      { id: '6', name: 'Francisca' },
      { id: '7', name: 'Gabriel' },
      { id: '8', name: 'Inês' },
      { id: '9', name: 'João' },
      { id: '10', name: 'Rafaela' },
    ],
  },
  {
    id: 6,
    name: 'Gargantua',
    guests: [
      { id: '1', name: 'Tia Cristina' },
      { id: '2', name: 'Tio Albano' },
      { id: '3', name: 'Tia Belém' },
      { id: '4', name: 'Tia Célia' },
      { id: '5', name: 'Tio Nelo' },
      { id: '6', name: 'Tio Adriano' },
      { id: '7', name: 'Tia Carmo' },
      { id: '8', name: 'Madrinha' },
      { id: '9', name: 'Sr. Manuel' },
      { id: '10', name: 'Tia São' },
      { id: '11', name: 'Namorado' },
    ],
  },
  {
    id: 7,
    name: 'The Tesseract',
    guests: [
      { id: '1', name: 'João' },
      { id: '2', name: 'Daniela' },
      { id: '3', name: 'Leo' },
      { id: '4', name: 'José' },
      { id: '5', name: 'Beatriz Abreu' },
      { id: '6', name: 'Ana' },
      { id: '7', name: 'Catarina' },
      { id: '8', name: 'Beatriz Leandro' },
      { id: '9', name: 'Pedro Leandro' },
      { id: '10', name: 'Namorada' },
    ],
  },
  {
    id: 8,
    name: 'Andromeda',
    guests: [
      { id: '1', name: 'Cátia' },
      { id: '2', name: 'Ricardo' },
      { id: '3', name: 'Camila' },
      { id: '4', name: 'Guilherme' },
      { id: '5', name: 'João' },
      { id: '6', name: 'Mulher' },
      { id: '7', name: 'Filho' },
      { id: '8', name: 'Cláudio' },
      { id: '9', name: 'Mulher' },
      { id: '10', name: 'Filha' },
    ],
  },
  {
    id: 9,
    name: 'Orion',
    guests: [
      { id: '1', name: 'Tia Lete' },
      { id: '2', name: 'Tia Rosa' },
      { id: '3', name: 'Tio César' },
      { id: '4', name: 'Tia Zefa' },
      { id: '5', name: 'Tio Manuel' },
      { id: '6', name: 'Tia Linda' },
      { id: '7', name: 'Tio Mingos' },
      { id: '8', name: 'Tio Sérgio' },
      { id: '9', name: 'Tia Lucia' },
      { id: '10', name: 'Avó Rorinha' },
    ],
  },
  {
    id: 10,
    name: 'Helix',
    guests: [
      { id: '1', name: 'Anselmo' },
      { id: '2', name: 'Mulher' },
      { id: '3', name: 'Filha' },
      { id: '4', name: 'Carina' },
      { id: '5', name: 'Tó' },
      { id: '6', name: 'Gonçalo' },
      { id: '7', name: 'Bruno' },
      { id: '8', name: 'Marlene' },
      { id: '9', name: 'Matilde' },
      { id: '10', name: '' },
    ],
  },
  {
    id: 11,
    name: 'Omega',
    guests: [
      { id: '1', name: 'Tiago' },
      { id: '2', name: 'Rui' },
      { id: '3', name: 'Daniel' },
      { id: '4', name: 'Helena' },
      { id: '5', name: 'Sara' },
      { id: '6', name: 'Davide' },
      { id: '7', name: 'Adriana' },
      { id: '8', name: 'João' },
      { id: '9', name: 'Leonor' },
      { id: '10', name: '' },
    ],
  },
  {
    id: 12,
    name: 'Orion',
    guests: [
      { id: '1', name: 'Sergio' },
      { id: '2', name: 'Helena' },
      { id: '3', name: 'Luisa' },
      { id: '4', name: 'Jose' },
      { id: '5', name: 'Susana' },
      { id: '6', name: 'Joao' },
      { id: '7', name: 'Leonel' },
      { id: '8', name: 'Ines' },
      { id: '9', name: 'Alice' },
      { id: '10', name: 'Vitor' },
      { id: '11', name: 'Serena' },
      { id: '12', name: 'Leo' },
    ],
  },
  {
    id: 13,
    name: 'Cassiopeia',
    guests: [
      { id: '1', name: 'Angelique' },
      { id: '2', name: 'Ricardo' },
      { id: '3', name: 'Afonso' },
      { id: '4', name: 'Luisa' },
      { id: '5', name: 'Sylviane' },
      { id: '6', name: 'Ricardo' },
      { id: '7', name: 'Matilde' },
      { id: '8', name: 'Clara' },
      { id: '9', name: 'Priscila' },
      { id: '10', name: 'Laura' },
    ],
  },
  {
    id: 14,
    name: 'Ursa Major',
    guests: [
      { id: '1', name: 'Tia Fátima' },
      { id: '2', name: 'Tio Ciano' },
      { id: '3', name: 'Tony' },
      { id: '4', name: 'Esmeralda' },
      { id: '5', name: 'Filho Tony' },
      { id: '6', name: 'Filho Tony' },
      { id: '7', name: '' },
      { id: '8', name: '' },
      { id: '9', name: '' },
      { id: '10', name: '' },
    ],
  },
  {
    id: 15,
    name: 'The Endurance',
    guests: [
      { id: '1', name: 'Quinel' },
      { id: '2', name: 'Fátima' },
      { id: '3', name: 'Bruna' },
      { id: '4', name: 'Armando' },
      { id: '5', name: 'Ana' },
      { id: '6', name: 'Filho Armando' },
      { id: '7', name: 'Filha Armando' },
      { id: '8', name: '' },
      { id: '9', name: '' },
      { id: '10', name: '' },
    ],
  },
  {
    id: 16,
    name: 'Lyra',
    guests: [
      { id: '1', name: 'Tia Fátima' },
      { id: '2', name: 'Oscar' },
      { id: '3', name: 'Mulher' },
      { id: '4', name: 'Filha' },
      { id: '5', name: 'Filha' },
      { id: '6', name: 'Tony' },
      { id: '7', name: 'Mulher' },
      { id: '8', name: 'Filho' },
      { id: '9', name: '' },
      { id: '10', name: '' },
    ],
  },
  {
    id: 17,
    name: 'Wormhole',
    guests: [
      { id: '1', name: 'Anabela' },
      { id: '2', name: 'Lucas' },
      { id: '3', name: 'Bruno' },
      { id: '4', name: 'Adriana' },
      { id: '5', name: 'Miguel' },
      { id: '6', name: 'Juliana' },
      { id: '7', name: 'Marco' },
      { id: '8', name: 'Sofia' },
      { id: '9', name: 'Bia' },
      { id: '10', name: 'Bruna' },
      { id: '11', name: 'Pedro' },
    ],
  },
];
