export interface Guest {
  id: string;
  name: string;
}

export interface Table {
  id: number;
  name: string;
  guests: Guest[];
  seats: number;
}

export type NewGuest = {
  name: string;
  table: number;
};

export type TableInfo = {
  number: number;
  name: string;
  guests: string[];
  x: string;
  y: string;
};

export const NewTables: TableInfo[] = [
  {
    number: 1,
    name: 'Andromeda',
    x: '78%',
    y: '24%',
    guests: [
      'Rosa',
      'Ângelo',
      'Anabela',
      'Pedro',
      'Ana Flor',
      'Feliciano',
      'Anđela',
      'Avó Emília',
      'Fátima',
    ],
  },
  {
    number: 2,
    name: 'Orion',
    x: '86%',
    y: '38%',
    guests: [
      'Palmira',
      'Aurélio',
      'Avô Chiquinho',
      'Avó Livinha',
      'Abílio',
      'Cristina',
      'Manuel',
      'Sandra',
      'Teresa',
      'José',
    ],
  },
  {
    number: 3,
    name: 'Hydra',
    x: '84%',
    y: '56%',
    guests: [
      'Emília',
      'Manuel',
      'Cristina',
      'Albano',
      'Célia',
      'Nelo',
      'Carmo',
      'Adriano',
      'Conceição',
      'Carlos',
      'Belém',
    ],
  },
  {
    number: 4,
    name: 'Cassiopeia',
    x: '72%',
    y: '72%',
    guests: [
      'José',
      'Beatriz',
      'Ana',
      'Catarina',
      'Beatriz L.',
      'Jorge',
      'Pedro',
      'João R.',
      'Daniela',
      'Leo',
    ],
  },
  {
    number: 5,
    name: 'Centaurus',
    x: '55%',
    y: '82%',
    guests: [
      'Tiago',
      'Sara',
      'Adriana',
      'João',
      'Leonor',
      'Beatriz S.',
      'Marcelo',
      'Beatriz C.',
      'Bruna',
      'Pedro',
    ],
  },
  {
    number: 6,
    name: 'Lyra',
    x: '38%',
    y: '82%',
    guests: [
      'Salete',
      'Rosa',
      'César',
      'Sérgio',
      'Lúcia',
      'Deolinda',
      'Domingos',
      'Avó Aurora',
    ],
  },
  {
    number: 7,
    name: 'Pegasus',
    x: '22%',
    y: '72%',
    guests: [
      'Sérgio',
      'Helena',
      'Luísa',
      'José',
      'Susana',
      'João',
      'Leonel',
      'Inês',
      'Alice',
    ],
  },
  {
    number: 8,
    name: 'Perseus',
    x: '12%',
    y: '56%',
    guests: [
      'Carina',
      'Tó',
      'Gonçalo',
      'Bruno',
      'Marlene',
      'Matilde',
      'Josefa',
      'Manuel',
    ],
  },
  {
    number: 9,
    name: 'Cepheus',
    x: '14%',
    y: '38%',
    guests: [
      'Sylviane',
      'Ricardo',
      'Matilde',
      'Clara',
      'Angelique',
      'Ricardo',
      'Afonso',
      'Luísa',
      'Priscila',
      'Laura',
    ],
  },
  {
    number: 10,
    name: 'Draco',
    x: '30%',
    y: '20%',
    guests: [
      'João Monteiro',
      'Liliana',
      'Daniel Costa',
      'Raquel Fernandes',
      'Henrique',
      'Raquel',
      'Diogo Costa',
      'Diogo Leite',
      'Eliana Magano',
      'Margarida',
      'Bruno',
      'Adriana',
      'Miguel Pinto',
      'Juliana',
      'Marco',
      'Sofia',
    ],
  },
  {
    number: 11,
    name: 'Aquila',
    x: '54%',
    y: '20%',
    guests: [
      'Margarida',
      'Paulinho',
      'Francisca',
      'João',
      'Estela',
      'Pedro',
      'Anabela',
      'Lucas Martins',
      'Mónica',
      'André',
      'Inês',
      'João',
      'Tiago',
      'Venus',
      'Francisca',
      'Gabriela',
      'José',
    ],
  },
];

export const TABLE_LAYOUT: Record<number, React.CSSProperties> = {
  // esquerda
  5: { left: '18%', top: '22%', width: '120px', height: '120px' },
  7: { left: '7%', top: '44%', width: '70px', height: '70px' },
  3: { left: '20%', top: '59%', width: '130px', height: '130px' },
  9: { left: '9%', top: '79%', width: '120px', height: '120px' },
  1: { left: '21%', top: '88%', width: '100px', height: '100px' },
  // direita
  8: { left: '93%', top: '25%', width: '70px', height: '70px' },
  6: { left: '83%', top: '37%', width: '90px', height: '90px' },
  4: { left: '89%', top: '61%', width: '140px', height: '140px' },
  2: { left: '83%', top: '86%', width: '130px', height: '130px' },
  // retangulares — left/right edges kept clear of PISTA (460–740px)
  11: { left: '34%', top: '50%', width: '80px', height: '490px' },
  10: { left: '66%', top: '47%', width: '80px', height: '380px' },
};

export const tables: Table[] = [
  {
    id: 1,
    name: 'Andromeda',
    guests: [
      { id: '1', name: 'Rosa Ramos' },
      { id: '2', name: 'Ângelo' },
      { id: '3', name: 'Anabela Ramos' },
      { id: '4', name: 'Pedro Ribeiro' },
      { id: '5', name: 'Ana Flor' },
      { id: '6', name: 'Feliciano Ramos' },
      { id: '7', name: 'Anđela Pušić' },
      { id: '8', name: 'Avó Emília' },
      { id: '9', name: 'Fátima' },
    ],
    seats: 10,
  },
  {
    id: 2,
    name: 'Orion',
    guests: [
      { id: '1', name: 'Aurélio Leandro' },
      { id: '2', name: 'Palmira Leandro' },
      { id: '3', name: 'Avô Chiquinho' },
      { id: '4', name: 'Avó Livinha' },
      { id: '5', name: 'Abílio Ribeiro' },
      { id: '6', name: 'Cristina Ribeiro' },
      { id: '7', name: 'Manuel Ribeiro' },
      { id: '8', name: 'Sandra Ribeiro' },
      { id: '9', name: 'Teresa' },
      { id: '10', name: 'José Silva' },
    ],
    seats: 10,
  },
  {
    id: 3,
    name: 'Hydra',
    guests: [
      { id: '1', name: 'Emília Silva' },
      { id: '2', name: 'Manuel' },
      { id: '3', name: 'Cristina Silva' },
      { id: '4', name: 'Albano Silva' },
      { id: '5', name: 'Célia Silva' },
      { id: '6', name: 'Nelo' },
      { id: '7', name: 'Carmo' },
      { id: '8', name: 'Adriano Silva' },
      { id: '9', name: 'Conceição Silva' },
      { id: '10', name: 'Carlos' },
      { id: '11', name: 'Belém Silva' },
    ],
    seats: 11,
  },
  {
    id: 4,
    name: 'Cassiopeia',
    guests: [
      { id: '1', name: 'Beatriz Abreu' },
      { id: '2', name: 'José Ribeiro' },
      { id: '3', name: 'Ana Leandro' },
      { id: '4', name: 'Catarina Silva' },
      { id: '5', name: 'Beatriz Leandro' },
      { id: '6', name: 'Jorge' },
      { id: '7', name: 'Pedro Leandro' },
      { id: '8', name: 'João Ribeiro' },
      { id: '9', name: 'Daniela Viana' },
      { id: '10', name: 'Leo' },
    ],
    seats: 10,
  },
  {
    id: 5,
    name: 'Centaurus',
    guests: [
      { id: '1', name: 'Tiago Silva' },
      { id: '2', name: 'Sara Silva' },
      { id: '3', name: 'Adriana Silva' },
      { id: '4', name: 'João Freitas' },
      { id: '5', name: 'Leonor' },
      { id: '6', name: 'Beatriz Silva' },
      { id: '7', name: 'Marcelo Pereira' },
      { id: '8', name: 'Beatriz Castro' },
      { id: '9', name: 'Bruna Mendes' },
      { id: '10', name: 'Pedro Ribeiro' },
    ],
    seats: 10,
  },
  {
    id: 6,
    name: 'Lyra',
    guests: [
      { id: '1', name: 'Salete Leandro' },
      { id: '2', name: 'Rosa Leandro' },
      { id: '3', name: 'César' },
      { id: '4', name: 'Lúcia' },
      { id: '5', name: 'Sérgio Leandro' },
      { id: '6', name: 'Deolinda Leandro' },
      { id: '7', name: 'Domingos' },
      { id: '8', name: 'Avó Aurora' },
    ],
    seats: 7,
  },
  {
    id: 7,
    name: 'Pegasus',
    guests: [
      { id: '1', name: 'Sérgio Santos' },
      { id: '2', name: 'Helena Ferreira' },
      { id: '3', name: 'Luísa' },
      { id: '4', name: 'José Santos' },
      { id: '5', name: 'Susana Pereira' },
      { id: '6', name: 'João' },
      { id: '7', name: 'Leonel Santos' },
      { id: '8', name: 'Inês Souta' },
      { id: '9', name: 'Alice' },
    ],
    seats: 9,
  },
  {
    id: 8,
    name: 'Perseus',
    guests: [
      { id: '1', name: 'Carina ' },
      { id: '2', name: 'António Bento' },
      { id: '3', name: 'Gonçalo' },
      { id: '4', name: 'Bruno ' },
      { id: '5', name: 'Marlene' },
      { id: '6', name: 'Matilde' },
      { id: '7', name: 'Josefa Leandro' },
      { id: '8', name: 'Manuel' },
    ],
    seats: 8,
  },
  {
    id: 9,
    name: 'Cepheus',
    guests: [
      { id: '1', name: 'Sylviane Rego' },
      { id: '2', name: 'Ricardo Guedes' },
      { id: '3', name: 'Matilde' },
      { id: '4', name: 'Clara' },
      { id: '5', name: 'Angelique Rego' },
      { id: '6', name: 'Ricardo Antunes' },
      { id: '7', name: 'Afonso' },
      { id: '8', name: 'Luísa' },
      { id: '9', name: 'Priscila Rego' },
      { id: '10', name: 'Laura' },
    ],
    seats: 10,
  },
  {
    id: 10,
    name: 'Draco',
    guests: [
      { id: '1', name: 'João Monteiro' },
      { id: '2', name: 'Liliana Machado' },
      { id: '3', name: 'Daniel Costa' },
      { id: '4', name: 'Raquel Fernandes' },
      { id: '5', name: 'Diogo Leite' },
      { id: '6', name: 'Eliana Santos' },
      { id: '7', name: 'Margarida' },
      { id: '8', name: 'Henrique ' },
      { id: '9', name: 'Raquel Carvalho' },
      { id: '10', name: 'Diogo Costa' },
      { id: '11', name: 'Bruno Faria' },
      { id: '12', name: 'Adriana Brito' },
      { id: '13', name: 'Miguel Pinto' },
      { id: '14', name: 'Juliana Covinha' },
      { id: '15', name: 'Marco Oliveira' },
      { id: '16', name: 'Sofia Campos' },
    ],
    seats: 16,
  },
  {
    id: 11,
    name: 'Aquila',
    guests: [
      { id: '1', name: 'Margarida Sousa' },
      { id: '2', name: 'Paulo Ferreira' },
      { id: '3', name: 'Francisca Barroso' },
      { id: '4', name: 'João Gonçalves' },
      { id: '5', name: 'Estela Novais' },
      { id: '6', name: 'Pedro Guimarães' },
      { id: '7', name: 'Anabela Araújo' },
      { id: '8', name: 'Lucas Martins' },
      { id: '9', name: 'Mónica Lopes' },
      { id: '10', name: 'André Monteiro' },
      { id: '11', name: 'Inês Martins' },
      { id: '12', name: 'João Carvalho' },
      { id: '13', name: 'Tiago Machado' },
      { id: '14', name: 'Venus' },
      { id: '15', name: 'Francisca Santos' },
      { id: '16', name: 'Gabriela Machado' },
      { id: '17', name: 'José Moreira' },
    ],
    seats: 17,
  },
];
